MovieShopMVC/Models/ErrorViewModel.cs
namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShopMVC/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using ApplicationCore.Models;
using ApplicationCore.Contracts.Services;
namespace MovieShopMVC.Controllers
{
    public class GenreController : Controller
    {
        private readonly IGenreService _genreService;
        public GenreController(IGenreService genreService)
        {
            _genreService = genreService;
        }
        public IActionResult Index()
        {
            ViewBag.CompanyName = "Antra";
            ViewData["CurrentDate"] = DateTime.Now;
            var data = _genreService.GetAllGenresAsync();
            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(GenreModel model)
        {
            if (ModelState.IsValid)
            {
                _genreService.InsertGenreAsync(model);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        
        public IActionResult Delete(int id)
        {
            try
            {
                _genreService.DeleteGenreAsync(id);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }
        }
    }
}

MovieShopMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Models;
using System.Diagnostics;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Notify()
        {
            return View("Contact");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShopMVC/Controllers/MovieController.cs
using ApplicationCore.Contracts.Services;
using ApplicationCore.Models;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Models;
namespace MovieShopMVC.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieService _movieService;
        public MovieController(IMovieService movieService)
        {
            _movieService = movieService;
        }
        public IActionResult Index()
        {
            var movies = _movieService.GetMoviesByPaginationAsync(10, 1, "");
            return View(movies);
        }
        [HttpGet]
        public IActionResult Genre(int id)
        { 
       var data =  _movieService.MoviesSameGenreAsync(id);
            return View(data);
        }

        [HttpGet]
        public IActionResult Create()
        { 
            return View();
        }
        [HttpPost]
        public IActionResult Create(MovieCreateRequestModel model)
        {
            try
            {
                _movieService.AddMovieAsync(model);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
            }
        }

       
    }
}

MovieShopMVC/Views/Genre/Create.cshtml
@using ApplicationCore.Models
@model GenreModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container">
    

<form method="post">
    <div class="row">
        <div class="mb-3">
        <input type="text" class="form-control" asp-for="Name" />
        </div>
    </div>
   
    <input type="submit" value="Genre" class="btn btn-info"/> 
</form>
</div>

MovieShopMVC/Views/Genre/Index.cshtml
@using ApplicationCore.Models
@model List<GenreModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@ViewBag.CompanyName <br/>
@ViewData["CurrentDate"]

<a href="/Genre/Create">Add New Genre</a>
<table class="table">
    <thead> <tr><th>Id</th> <th>Name</th> <th colspan="3">Options</th> </tr> </thead>
    <tbody>
        @foreach (var m in Model)
        {
            <tr> <td>@m.Id</td> <td>@m.Name</td> <td>  <a href="" > <span class="bi bi-tools"></span>  Edit</a> </td>
                
            <td> <a href="">Details</a> </td> 
            <td> <a href="/Genre/Delete/@m.Id">Delete</a> </td> 
            </tr>

        }
    </tbody>
</table>

MovieShopMVC/Views/Home/Contact.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>This is contact us page</h3>
<p>YOu can call us at our 24X7 number 7896543210</p>

MovieShopMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>This is another paragraph</p>
    hi there
</div>

MovieShopMVC/Views/Movie/Create.cshtml
@using ApplicationCore.Models
@model MovieCreateRequestModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@*
   @using (@Html.BeginForm("action","controller", httpverb))
   {

   }
*@

@using (@Html.BeginForm("Create","Movie",FormMethod.Post))
{
    <span>Title</span>
    @Html.EditorFor(m=>m.Title)
    @Html.ValidationMessageFor(m=>m.Title)<br/>
    <span>Overview</span>
    @Html.TextAreaFor(m=>m.Overview)
    @Html.ValidationMessageFor(m=>m.Overview)<br/>
    
    <span>Tagline</span>
    @Html.TextBoxFor(m=>m.Tagline)
    @Html.ValidationMessageFor(m=>m.Tagline)<br/>
    
    <span>Revenue</span>
    @Html.TextBoxFor(m=>m.Revenue)
    @Html.ValidationMessageFor(m=>m.Revenue)<br/>

    <span>Budget</span>
    @Html.TextBoxFor(m=>m.Budget)
    @Html.ValidationMessageFor(m=>m.Budget)<br/>

    <span>Imdb url</span>
    @Html.TextBoxFor(m=>m.ImdbUrl)
    @Html.ValidationMessageFor(m=>m.ImdbUrl)<br/>

    <span>TmdbUrl</span>
    @Html.TextBoxFor(m=>m.TmdbUrl)
    @Html.ValidationMessageFor(m=>m.TmdbUrl)<br/>

    <span>PosterUrl</span>
    @Html.TextBoxFor(m=>m.PosterUrl)
    @Html.ValidationMessageFor(m=>m.PosterUrl)<br/>

    <span>BackdropUrl</span>
    @Html.TextBoxFor(m=>m.BackdropUrl)
    @Html.ValidationMessageFor(m=>m.BackdropUrl)<br/>

    <span>Original language</span>
    @Html.TextBoxFor(m=>m.OriginalLanguage)
    @Html.ValidationMessageFor(m=>m.OriginalLanguage)<br/>

    <span>Run time</span>
    @Html.TextBoxFor(m=>m.RunTime)
    @Html.ValidationMessageFor(m=>m.RunTime)<br/>
    
    <span>Price</span>
    @Html.TextBoxFor(m=>m.Price)
    @Html.ValidationMessageFor(m=>m.Price)<br/>

    <input type="submit" value="Save Movie"/>

}

MovieShopMVC/Views/Movie/Genre.cshtml
@using ApplicationCore.Models;
@model List<MovieCardResponseModel>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>Movies with the same genre</h3>
<div class="container">
    <div class="row">
        @foreach (var m in Model)
        {

            <partial name="_MovieCard" model="m"></partial>
        }
    </div>
</div>

MovieShopMVC/Views/Movie/Index.cshtml
@using ApplicationCore.Models
@model PagedResultSet<MovieCardResponseModel>

@*
    For morebottomation on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h2>Movies</h2>
<a href="/">Add New Movie</a>
<table>
    @{
        <div class="row">
        @foreach (var m in Model.Data)
        {

            <div class="card col-3" style="margin-right:2px; margin-bottom:5px;" >
            
                <img src="@m.PosterUrl" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">@m.Title</h5>

                </div>
            </div>


        }
        </div>

    }



</table>

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MovieShopMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genre</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="card mb-4">
    <a asp-controller="Movie" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" />
    </a>

</div>